baseurl = "https://saurvs.github.io/"
title = "Saurav Sachidanand"
languageCode = "en-us"
theme = "meh"

[Params]
  subtitle = "Y = λf. ( λ☃. f (☃ ☃) ) ( λ☃. f (☃ ☃) )"

[author]
    name = "Saurav Sachidanand"
    email = "sauravsachidanand@gmail.com"
    github = "saurvs"
    linkedin = "in/saurvs"

[[menu.main]]
    name = "Blog"
    url = "/"
    weight = 1

[[menu.main]]
    name = "About"
    url = "/page/about"
    weight = 2
